"""empty message

Revision ID: ef163efc9238
Revises: 
Create Date: 2023-04-22 05:33:31.531961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ef163efc9238'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('company', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fname', sa.String(), nullable=False),
    sa.Column('lname', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('developer', 'admin', name='roletype'), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_modified_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('document_metadata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.UUID(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('documentPath', sa.String(), nullable=False),
    sa.Column('documentFileName', sa.String(), nullable=False),
    sa.Column('mimeType', sa.String(), nullable=False),
    sa.Column('uploadedAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('lastUpdatedAt', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('uploadedByUserId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['customerId'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['uploadedByUserId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customerId', 'documentId')
    )
    op.create_index(op.f('ix_document_metadata_customerId'), 'document_metadata', ['customerId'], unique=False)
    op.create_index(op.f('ix_document_metadata_documentId'), 'document_metadata', ['documentId'], unique=False)
    op.create_table('document_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customerId', sa.UUID(), nullable=False),
    sa.Column('documentId', sa.Integer(), nullable=False),
    sa.Column('documentContentHash', sa.String(), nullable=False),
    sa.Column('documentMetadataHash', sa.String(), nullable=False),
    sa.Column('ingestionStatus', sa.Enum('STARTED', 'SUCCEEDED', 'FAILED', name='ingestionstatusenum'), nullable=False),
    sa.Column('extractionStatus', sa.Enum('STARTED', 'SUCCEEDED', 'FAILED', name='extractionstatusenum'), nullable=False),
    sa.Column('logs', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['customerId'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('customerId', 'documentId')
    )
    op.create_index(op.f('ix_document_status_customerId'), 'document_status', ['customerId'], unique=False)
    op.create_index(op.f('ix_document_status_documentId'), 'document_status', ['documentId'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_document_status_documentId'), table_name='document_status')
    op.drop_index(op.f('ix_document_status_customerId'), table_name='document_status')
    op.drop_table('document_status')
    op.drop_index(op.f('ix_document_metadata_documentId'), table_name='document_metadata')
    op.drop_index(op.f('ix_document_metadata_customerId'), table_name='document_metadata')
    op.drop_table('document_metadata')
    op.drop_table('users')
    op.drop_table('customers')
    # ### end Alembic commands ###
